### ISSUE TITLE
Require user authentication

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#1]
Update web.config for this application so users are required to be authenticated. We can share Forms authentication cookies on the insitesystems.com domain, so if a user is authenticated in Iris then he should be authenticated here automatically.

We shouldn't need to make any code changes to implement this; I think it should require only configuration file changes.

I want this project to remain public so one problem we need to solve is how we can configure the same machine key in web.config for both applications (Iris and Lotus) without including the machine key in the source code (or anywhere in the repo).  

Perhaps we can execute a PowerShell script whenever we run a deployment, which reads machine key configuration settings from a file in a secure location on the file system?  I'm open to your ideas and suggestions here.

**Comment by Oleg-Terzi** [comment]
> Perhaps we can execute a PowerShell script whenever we run a deployment, which reads machine key configuration settings from a file in a secure location on the file system? I'm open to your ideas and suggestions here.

I think we could use "Web.config File Transformations" feature for this purpose.
For example, you could remove .\Source\Lotus\Web.Release.config file from repository (__not from the project__) and leave it only for your own project copy. There you could set up the settings we want to see on Production environment.

For anyone who will clone the Lotus from GitHub the Web.Release.config file will be shown as missed:
![Web.config file is missed](https://cloud.githubusercontent.com/assets/5382331/14709206/253a71b2-07d8-11e6-8a84-7aac05629206.png)

But the project will be successfully compiled with no errors or warnings:
![No errors when you build the project](https://cloud.githubusercontent.com/assets/5382331/14709242/4dbb2a64-07d8-11e6-9ca0-56bcdf1be14c.png)


It seems to me more easier (and flexible as yours) solution.

**Comment by Daniel-Miller** [comment]
I like your solution better than mine: it's much simpler and easier to manage. Let's proceed with your proposal.

**Comment by Oleg-Terzi** [comment]
The task is completed but changes are not committed yet (I have no write-access to this repository).

To set up the Single Sign-On solution you need:

1. Enable HTTPS for Lotus website.

2. Generate the decryption/validation keys for Local and Demo environments and put them to this web.config section (for all InSite apps like Focus/Iris/Lotus etc):
    ![web config](https://cloud.githubusercontent.com/assets/5382331/14717361/d53b30c6-07f9-11e6-87dc-c5918d4b4577.png)

3. Generate the decryption/validation keys for Production environments and put them to the same section of web.__release__.config file (for all InSite apps).

4. I added code to the Iris application that will redirect the user back to Lotus when it came from Lotus to sign-in. So you need update Iris app as well.

Also I found (and fixed) a little layout issue:
- Before fix:
    ![before fix](https://cloud.githubusercontent.com/assets/5382331/14717851/0b304c00-07fc-11e6-8c49-a995642825a6.png)

- After fix:
    ![after fix](https://cloud.githubusercontent.com/assets/5382331/14717860/15ae3750-07fc-11e6-8f36-a480ff505949.png)

**Comment by Oleg-Terzi** [comment]
Done.

**Comment by Daniel-Miller** [comment]
Excellent - and thanks for the cosmetic fix.  I missed that.
