### ISSUE TITLE
Create a new Dependency/Visualize controller and view

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#10]
After Issue #9 is complete, we need to add an icon (fa-exchange) button beside each activity in the Program/Display hierarchy.

When you click this icon a popup window should open to a new view (Dependency/Visualize) for the selected activity.

This popup window should display a select input (Distance) and a Submit button. The select should include N items, with values 1..N, where N is the longest distance from the selected activity to any other activity in the graph.  (Perhaps we will want to generate and use pre-computed route tables for this?)

The default value should be 2.

When you click Submit, the page should display a network graph for a specific subset of nodes and edges from the overall graph (Activities/Graph.json). The graph should include the selected node and the nodes that can be reached from the selected node by traversing 1..Distance edges. The graph should also display the edges as directed edges.

Let me know if this makes sense. 

Here are some basic prototypes:

http://graph.insitesystems.com/vis/SmallTest.html
http://graph.insitesystems.com/vis/BigTest.html

And here is the library I'm using:

http://visjs.org/network_examples.html

**Comment by Oleg-Terzi** [comment]
Done.
Please note: the Graph.json contains a lot of duplicates of nodes and edges. I created an utility that removed all duplicates from Graph.json. There in attachment is archive with fixed Graph.json and code of utility for removing duplicates.

[Issue9_20160510.zip](https://github.com/InSite/Lotus/files/257992/Issue9_20160510.zip)

**Comment by Daniel-Miller** [comment]
I'm not able to unzip the file. Could you try re-zipping and re-attaching?

We should program the Admin controller to auto-fix duplicate nodes and edges.  I'm seeing two unhandled exceptions in my local environment:

[Data-Files_Lotus.zip](https://github.com/InSite/Lotus/files/258066/Data-Files_Lotus.zip)

![ex1](https://cloud.githubusercontent.com/assets/5367871/15161325/f3648960-16ba-11e6-8933-3d58993c64cb.png)
![ex2](https://cloud.githubusercontent.com/assets/5367871/15161326/f38de7d8-16ba-11e6-8041-afd0d192f58e.png)

**Comment by Oleg-Terzi** [comment]
Here is fixed archive:
[Issue10_20160511.zip](https://github.com/InSite/Lotus/files/258171/Issue10_20160511.zip)
Now it should be opened with no issues.

I will add the auto-fix feature to Admin controller tomorrow morning.

Note: I fixed the second exception (Sequence contains no elements) and the first exception should be fixed by new Graph.json.

**Comment by Oleg-Terzi** [comment]
I added a new button on Admin/Index page:
![img_1](https://cloud.githubusercontent.com/assets/5382331/15175776/917d4cda-1770-11e6-9a13-45cf20f35662.png)
If you click it the system will remove duplicates from Graph.json.

**Comment by Daniel-Miller** [comment]
I really like your solution here, and having the graph open in a new window (rather than a popup window) is a better idea.  I found 3 improvements we should make before we show this to our users:

1. The edges in the graph should be directed, so we should show an arrow to show direction. 

2. We should also show a label on the edge in small font size (ActivityGraphEdge.Verb).

3. The graph should include incoming edges as well as outgoing edges.  Currently it seems to traverse only outgoing edges from the selected node, and it should traverse incoming edges also.  The idea here is to allow a user to see all the relationships (from and to) the node he has selected.

**Comment by Oleg-Terzi** [comment]
Done.
