### ISSUE TITLE
Make a minor imporvement to the tree-view style (if possible)

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#11]
This is a very minor cosmetic issue, and we don't need to spend a lot of time on this. Is it possible for us to keep text indented when it wraps to multiple lines?

For example this:
![wrap](https://cloud.githubusercontent.com/assets/5367871/15093126/e913d06a-143a-11e6-84a1-3eb45b970f3e.png)

... would look better like this:
![wrap-indent](https://cloud.githubusercontent.com/assets/5367871/15093125/e63b6a2e-143a-11e6-8ba6-527344fc3718.png)

**Comment by Oleg-Terzi** [comment]
Done.

**Comment by Daniel-Miller** [comment]
Perfect - this looks amazing
