### ISSUE TITLE
Improve the graph in the new dependency/visualize 

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#14]
1. The label on a node in the Graph should be the activity number, not the activity title.

2. When you hover over a node you should see the activity title. For example, hover over the node "Mick" in this example - http://visjs.org/examples/network/data/scalingNodesEdges.html

Perhaps we can make this configurable? So the user can choose if he wants activity number or activity title for node labels? Then if he chooses number, the tool-tip shows title - and if he chooses title then the tool-tip shows number.

**Comment by Oleg-Terzi** [comment]
Done.

**Comment by Daniel-Miller** [comment]
Is all the latest source pushed to the repo? Is there anything I need to do to refresh or reload my local JSON files? I get an error on some nodes, and the toggle for labels (Number/Title) doesn't seem to be working on my end.
![number](https://cloud.githubusercontent.com/assets/5367871/15222146/359c0c7c-1823-11e6-94b6-a653aaf7db8e.png)
![undefined](https://cloud.githubusercontent.com/assets/5367871/15222147/35aa8b9e-1823-11e6-8d54-c757008f17d0.png)

**Comment by Daniel-Miller** [comment]
Here are few things I tried:

- I re-pulled the source code from GitHub and recompiled
- I cleared my local browser cache
- I re-executed the Publish function on the admin/activity/home page in Iris
- I re-executed the Publish function on the admin/activity/edit page in Iris for the Power Engineering Skills Development Plan
- I executed the system/restart action on Lotus
- I executed the Fix Graph action on the Lotus Admin view

These steps didn't seem to have an effect.

**Comment by Oleg-Terzi** [comment]
> I get an error on some nodes

I found and fix this bug.

> the toggle for labels (Number/Title) doesn't seem to be working on my end.

I can't reproduce this bug:


![img_1](https://cloud.githubusercontent.com/assets/5382331/15223497/742fb8bc-187d-11e6-9c1e-0327d1731498.png)
![img_2](https://cloud.githubusercontent.com/assets/5382331/15223504/7b1e5994-187d-11e6-9cdb-5046f599cf54.png)

Did you click Submit button after you have selected the Label selector value?
