### ISSUE TITLE
Apply color-coding to the edges in the graph

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#17]
If an edge has Condition = "On Success" then color the edge green.

If an edge has Condition = "On Failure" then color the edge red.

If an edge has Descriptor = "is in" then use a dashed line rather than a solid line (e.g. http://visjs.org/examples/network/edgeStyles/arrows.html)

![edges](https://cloud.githubusercontent.com/assets/5367871/15382290/150b0f58-1d46-11e6-9f16-93a908772e1e.png)

**Comment by Oleg-Terzi** [comment]
Done.
