### ISSUE TITLE
Update the Program/Display view to work with the updated document storage

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#19]
![display](https://cloud.githubusercontent.com/assets/5367871/15663814/ed22bea8-26bb-11e6-85a0-985260d9c63e.png)

**Comment by Oleg-Terzi** [comment]
I can't reproduce this bug -- it seems that it was fixed previously.

**Comment by Daniel-Miller** [comment]
I can't reproduce it now either. You or I must have fixed this as a side-effect of other changes yesterday. :-)
