### ISSUE TITLE
Add a new Quiz property to limit the number of submissions per user

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#2]
Add a new property to the Quiz entity: 

int MaximumSubmissionsPerUser (default = 1)

When you start a lesson that is a Quiz, you should see a new quiz if you have submitted < MaximumSubmissionsPerUser.

Otherwise you should see the Score view for the last quiz you submitted.

**Comment by Oleg-Terzi** [comment]
Done.
