### ISSUE TITLE
Implement drag-and-drop feature for uploading documents and images

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#21]
1. In the Lotus.Web.Author project, allow the user to edit the Document Name

2. Beside the Document Name, display another field labeled "Tenant Name"

3. Implement the drag and drop functionality to upload files and create the markdown syntax for links and images that we have on the admin/quiz/question/edit form in Iris.  We should match the functionality we have on the admin/quiz/question/edit page.  This will allow our users to include document links and images in their content.  Note: uploaded files should be stored under ~/Uploads/Tenants/TenantName

![upload](https://cloud.githubusercontent.com/assets/5367871/15684226/5db1de3a-2723-11e6-9496-80f7cdf93170.png)

**Comment by Oleg-Terzi** [comment]
Done.
