### ISSUE TITLE
Add a style selector

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#22]
Add a combo box to the top right in the Preview column labeled "Style" with three options: Style 1 (default); Style 2; Style 3

Each of these options should correspond to a CSS file with rules defined for the content in the Preview column.  

This will enable the user to choose from one of three available content 'themes' (which we will define).  To start, we can define some very basic and simple rules -- e.g., font style, font size, and font color.

![style](https://cloud.githubusercontent.com/assets/5367871/15685764/700c9b2c-272a-11e6-93f5-b438d3bf4f46.png)

**Comment by Daniel-Miller** [comment]
In our example styles let's remember to include CSS rules for "signature" and "purpose", as in the example for Issue #24.

**Comment by Daniel-Miller** [comment]
I like where you have placed the Document Type label and selector. Let's put the Style label and selector beside the Document Type label and selector (instead of where I proposed in my mockup above).

**Comment by Oleg-Terzi** [comment]
Done.
