### ISSUE TITLE
Add support for a Survey-Link placeholder

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#23]
This improvement has some similarity to the enhancement described in Issue #20, and I think we might want to create a file or a table that contains our "Content Replacement Rules"?

For example, when an administrator authors a survey invitation message using this application, he might want to add a placeholder for a survey link.

{Survey-Link}

This placeholder would be replaced with HTML like you see in the attached file.

[Survey-Link.txt](https://github.com/InSite/Lotus/files/291911/Survey-Link.txt)

**Comment by Oleg-Terzi** [comment]
I improved a little this placeholder so if the user want to put a survey key directly into HTML then the user should use the next syntax: {Survey-Link**#SURVEY-KEY**}
For example:
![img_1](https://cloud.githubusercontent.com/assets/5382331/15905215/c1639fd2-2dbc-11e6-8a33-b9742ba76b4a.png)
