### ISSUE TITLE
Enhance the Section-Break feature

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#24]
Improve the functionality described in Issue #20 by allowing an optional ":identifier" in the {Section-Break} token. For example:

{Section-Break:signature}

This will include a CSS class attribute in the replacement HTML. For example:

`<table class="signature"><tr><td>`

This will enable the content author to apply custom styles to specific content sections. For example, here we might use {Section-Break:purpose} for the section with the blue background, and we might use {Section-Break:signature} for the section with the dark background.

![example](https://cloud.githubusercontent.com/assets/5367871/15687281/1fb9551e-2731-11e6-8c97-0cf1ae8a45c6.png)

**Comment by Oleg-Terzi** [comment]
Done.
