### ISSUE TITLE
Add a selector above the input control in the left column titled Placeholder

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#25]
This should be a drop-down list with the following items:

Section Break
Column Break
Survey Link

Company Abbreviation
Company Name
Company Web Site
Company Email
Company Address
Company Logo

Recipient First Name
Recipient Last Name
Recipient Email

Sender Name
Sender Email

When you select one of these items, client-side script should insert the corresponding placeholder into the content (at the current cursor location).

For example, if you select "Recipient First Name" then this placeholder text is inserted: "{Recipient-First-Name}".

This will help to ensure users know what placeholders we will support (especially for email messages), and help so they don't need to remember the exact syntax for a placeholder.

**Comment by Oleg-Terzi** [comment]
Done.
