### ISSUE TITLE
Create a new view: Program/Report

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#26]
This view will be similar to the program/display view, with the following changes:

1. Remove the Search section. This view will display only the program identified by the id in the URL.

2. The entire hierarchy should be expanded by default. 

3. Remove the Show Dependencies button

4. Show my score for each task (where the Show Dependencies icon was displayed).

5. Show a green check icon beside my score if the task is successfully complete. Otherwise display a red times icon ("x").

6. Disable the selection function in the tree view.  The user does not need to select/highlight nodes in the tree here.

7. Modify the Admin/Index view: remove the link from the program title and add two icons: one that links to Program/Display and one that links to Program/Report.

**Comment by Oleg-Terzi** [comment]
Done.
