### ISSUE TITLE
Move the ContentTool controller and views from Lotus.Web.Connector to Lotus.Web

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#27]
ContentTool should be renamed Link.  Here are the actions we need on the LinkController:
 
- Index
- Create
- Edit
- Detail
- Delete
- Launch
- LaunchMoodle

Then we can remove the old Lotus.Web.Connector project from the solution and delete it from the repo.

**Comment by Daniel-Miller** [comment]
Maybe it will be simpler and easier to copy the code we need from the Lotus.Web.Connector project into the Lotus.Web project -- and then delete the Lotus.Web.Connector project?  

I would like to merge these two projects eventually, but I don't want a lot of messy code (which we didn't write and which we don't need) copied into the Lotus.Web project (which we have kept very clean).  

Let me know what approach you prefer here.

**Comment by Oleg-Terzi** [comment]
Done.

**Comment by Daniel-Miller** [comment]
This looks great - nice work. I have dropped the Lotus.Web.Connector project from the Lotus solution.
