### ISSUE TITLE
Refactor the Lotus database for the Lotus.Web.Connector project

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#28]
1. Remove the Owner_Id column from the ContentTools table.

2. Rename the ContentTools table to dbo.Link.  (This table stores links to content stored in exteneral training delivery systems.)

3. Rename the ContentController to LinkController.

**Comment by Daniel-Miller** [comment]
I have started working on this issue today. I have dropped all the tables we don't need from the Lotus database, and I have removed a lot of classes we don't need from the codebase for this application.

DROP TABLE dbo.AspNetUserClaims
DROP TABLE dbo.AspNetUserLogins
DROP TABLE dbo.AspNetUserRoles
DROP TABLE dbo.AspNetRoles
ALTER TABLE dbo.ContentTools DROP CONSTRAINT [FK_dbo.ContentTools_dbo.AspNetUsers_Owner_Id]
DROP INDEX IX_Owner_Id ON dbo.ContentTools
ALTER TABLE dbo.ContentTools DROP COLUMN Owner_Id
DROP TABLE dbo.AspNetUsers

**Comment by Oleg-Terzi** [comment]
Done.
