### ISSUE TITLE
Implement basic score calculation and display for simple quizzes

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#3]
My test quiz is accessible via this URL --
https://local-lotus.insitesystems.com/lesson/test-program/module-x/1

**Comment by Daniel-Miller** [comment]
When you answer a question incorrectly, if the question has a non-null Hint then the Score view should display the Hint below the radio button list.

**Comment by Oleg-Terzi** [comment]
The task is completed. I made some changes to the code to avoid usage of session and now the system has next behaviour:

1. When a user goes by link to the quiz, the system creates a unique copy of the quiz that contains only questions and options that will be displayed to the user (please see _Create_ method of _UserQuiz_ class). The copy of quiz will be signed with a timestamp and then stored by following path:

    ~/content/users/\<USER_NAME\>/Quiz/\<QUIZ_TIMESTAMP\>/

    For example:
	
	![img_1](https://cloud.githubusercontent.com/assets/5382331/14752980/fa945e2e-08da-11e6-94bd-e475153030f4.png)
	
2. Then a user will be redirected to the quiz copy:

    ![img_2](https://cloud.githubusercontent.com/assets/5382331/14752991/0483b83a-08db-11e6-8fd3-c924e0967e79.png)
	
	Where _7125524982ba2_ value in the query string is timestamp of the quiz.
	
3. And finally when a user clicks Sumbit button the system will create a response result storage object (please see _UserResponse_ class) and save it to the same folder. 

Using this behaviour we will avoid possible data conflicts, we can be sure that we will see the quiz in the same way that a user have seen it during passing of the quiz, and the quiz results will be accessible at any time through the quiz timestamp.

Please let me know if you have any suggestions and/or remarks on this work.
