### ISSUE TITLE
Integrate the Exceptionless API

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#3]
Here we can use the same API Key that we use for the Iris project.

Wc3s64uke0lIIU8qlR2tgkOCtFGSlHMoikuWfTDo

**Comment by Oleg-Terzi** [comment]
Done.

**Comment by Oleg-Terzi** [comment]
I forgot to remind you - we need to enable the Exceptionless for Live and Demo environments (in web.*.config file):

![img_1](https://cloud.githubusercontent.com/assets/5382331/14859905/e137c704-0cae-11e6-8283-70d97f9651cf.png)

And probably, we need to remove the API key from the current web.config and the body of this issue.

**Comment by Daniel-Miller** [comment]
Good catch. We should move the Exceptionless configuration settings into Web.Live.config (and make sure those are excluded from the GitHub repo).
