### ISSUE TITLE
Add a Search Criteria section to the Link/Index page

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#30]
The layout, style, and functionality should follow a similar pattern to the one we use on the Task/Index page in the Snap.Web application.  

However, we do *not* want to use any Telerik components in the Lotus application.  I want to keep Lotus a "Telerik-free" zone!  :-)

**Comment by Oleg-Terzi** [comment]
Done.

**Comment by Daniel-Miller** [comment]
This looks great - nice work. Can we make two minor improvements here:

1. By default the search input should be blanks, so all search results are visible when the page loads for the first time.

2. The user's search criteria should be saved in session state, so when he returns to this page later in his session, by default it shows the criteria (and the search results) for his last search.

**Comment by Oleg-Terzi** [comment]
Done.

**Comment by Daniel-Miller** [comment]
Did I break this or overwrite this by mistake? When I test this my search criteria isn't saved in session state.

**Comment by Oleg-Terzi** [comment]
> Did I break this or overwrite this by mistake?

My changes was overwritten and I restored them.

**Comment by Daniel-Miller** [comment]
I'm not sure how I managed to overwrite the changes - sorry about that.  It's working great now - thanks.
