### ISSUE TITLE
Modify the data binding for the program dropdown on the Admin/Index view

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#4]
Currently, the dropdown here is a hard-coded list. Instead it should display an item for each folder in the virtual directory ~/Content/Courses/

Instead the data binding here should be dynamic:

1. The text displayed to the user should be be the course's Title (this can be found in the course directory's index.json file)

2. The value that binds to the user's program should be the directory name (which should also match the Name attribute in the course directory's index.json file).

**Comment by Oleg-Terzi** [comment]
Done.
