### ISSUE TITLE
Add a new controller and view: Calendar/Test

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#8]
This is an admin-only page that will be used to create and test iCalendar files (.ics).

https://en.wikipedia.org/wiki/ICalendar

The view should display input fields for Date, Start Time, End Time, Organizer, Summary, Description, Attendees. When you modify these input values the view should display the raw text for the ICS file, which you should be able to modify.  

Next you should be able to click a Test button to download the ICS content in an ICS file.

The idea here is our administrators need to run various manual tests in order to get an ICS file that produces specific behaviour in programs like Outlook, Gmail, and iMail.

**Comment by Oleg-Terzi** [comment]
The task is completed. The new screen is here:
https://local-lotus.insitesystems.com/calendar/test

Please note: I use here Bootstrap 3 Datepicker component (http://eonasdan.github.io/bootstrap-datetimepicker/) because it allows us to select the time and date individually.
