### ISSUE TITLE
Create a new Program/Display controller and view

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Lotus#9]
The attached zip folder contains a snapshot of my local Data/Files/Lotus directory.  

[Data-Files-Lotus.zip](https://github.com/InSite/Lotus/files/251055/Data-Files-Lotus.zip)

Notice:

- The Activities/Graph.json file contains the entire set of activity entities for the BCIT tenant account, so that we can create an in-memory Graph object that models the entire data set using nodes and edges.

- The Programs folder contains a JSON file for each "program" activity (i.e. the parent/child hierarchy for all composite activities).

These files are generated by a new Publish feature in Iris.  For reference, see the activity/home page.

The Admin/Index view shows a listing of the program activities. As a next step, we need to implement these few enhancements:

1. The list of programs should be sorted alphabetically.

2. The activity count should include all descendants (excluding the root node).

3. Create a Program controller and a Display view. Each program title should be a link to the new Program/Display action.

4. The Program/Display view should display the selected program using the Default template for the Bootstrap Tree View -- http://jonmiles.github.io/bootstrap-treeview/

5. The Program/Display view should include a Search function, as in the Searchable Tree section, where we can enter a keyword and the matching search results are highlighted (and displayed under Results).

6. The Program/Display view should include an Expand All and Collapse All function (as in the Expandible Tree section), so you can select a depth level and then expand or collapse the tree to that level.

**Comment by Daniel-Miller** [comment]
You have probably noticed already, but I have written ActivityTree and ActivityGraph classes, which we should use here too.

**Comment by Oleg-Terzi** [comment]
Done.

**Comment by Oleg-Terzi** [comment]
Please note: programs are cached in memory so the system doesn't need to reload them each time. If file's timestamp is changed or file is deleted then the system will update data for this program. For details please see Get method of ProgramRepository class:
https://github.com/InSite/Lotus/blob/master/Source/Lotus.Web/Repositories/ProgramRepository.cs

**Comment by Daniel-Miller** [comment]
This looks great - nice work. We need just to improvements:

1. Exclude the root from the tree view, and display the name of the root node where we currently display "Tree" in an h3 element.

2. Add a depth level selector so when you click Expand All you can expand the tree to that level.

![expand](https://cloud.githubusercontent.com/assets/5367871/15093045/9f5e729c-1438-11e6-9631-35cb93b22cdd.png)

**Comment by Oleg-Terzi** [comment]
Done.
